toggl:
# API Tokenは https://track.toggl.com/profile から取得できる
  token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# WorkspaceIDは「Manage Workspaces」から対象のWorkspaceを選び、URLの /workspaces/[数値]/ の[数値]の部分
  workspace_id: XXXXXXXX

skip_project_ids:
# 集計除外するプロジェクトIDを指定する
# ProjectIDは「MANAGE → Projects → プロジェクトをクリック」し、URLの /projects/[数値]/ の[数値]の部分
# 省略可
  - XXXXXXXX # 休憩

worktimes:
  min: "140h"   # 最低稼働時間
  max: "180h"   # 最高稼働時間
  rest: "1h"    # 標準の休憩時間
  start: "9:00" # 標準の就業時間
  end: "18:00"  # 標準の終業時間
  round: "15m"  # 時間単位

# 日本の祝日
holidays:
  - { date: 2023-10-09, name: "スポーツの日" }
  - { date: 2023-11-03, name: "文化の日" }
  - { date: 2023-11-23, name: "勤労感謝の日" }
  - { date: 2023-12-31, name: "大晦日" }
